---
test_zabbix:
  type: "array"
  description: "A list of device UIDs to poll metrics for."
  items:
    type: "object"
    properties:
      customer_id:
        description: "Customer id."
        type: "string"
      zabbix_url:
        description: "zabbix api url."
        type: "string"  
      api_key:
        description: "Your access token secret."
        type: "string"
  required: true