---
test_zabbix:
  description: "Configuration to authenticate with Zabbix Server"
  type: "object"
  required: true
  patternProperties:
    "^.*$":
      description: "Customer id"
      type: "object"
      properties:
        zabbix_url:
          description: "zabbix api url"
          type: "string"
          required: true  
        api_key:
          description: "zabbix api token"
          type: "string"
          required: true
          secret: true
  